apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: {{ include "opentenbase.name" . }}
  annotations:
    kubeblocks.io/extra-env: '{"DATANODE_COUNT":"2", "COORDINATOR_COUNT":"1"}'
spec:
  clusterDefinitionRef: opentenbase
  clusterVersionRef: opentenbase-{{ default .Chart.AppVersion .Values.clusterVersionOverride }}
  terminationPolicy: {{ .Values.terminationPolicy }}
  componentSpecs:
    - name: gtm
      componentDefRef: gtm
      replicas: {{ .Values.gtm.replicas }}
      {{- with  .Values.gtm.resources }}
      resources:
        {{- with .limits }}
        limits:
          cpu: {{ .cpu | quote }}
          memory: {{ .memory | quote }}
        {{- end }}
        {{- with .requests }}
        requests:
          cpu: {{ .cpu | quote }}
          memory: {{ .memory | quote }}
        {{- end }}
      {{- end }}
      {{- if .Values.gtm.persistence.enabled }}
      volumeClaimTemplates:
        - name: data   # ref clusterdefinition components.containers.volumeMounts.name
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: {{ .Values.gtm.persistence.data.size }}
      {{- end }}
    {{- $i := 0 }}
    {{- range .Values.dn }}
    - name: dn-{{ $i }}
      componentDefRef: dn
      replicas: {{ .replicas }}
      {{- with  .resources }}
      resources:
        {{- with .limits }}
        limits:
          cpu: {{ .cpu | quote }}
          memory: {{ .memory | quote }}
        {{- end }}
        {{- with .requests }}
        requests:
          cpu: {{ .cpu | quote }}
          memory: {{ .memory | quote }}
        {{- end }}
      {{- end }}
      {{- if .persistence.enabled }}
      volumeClaimTemplates:
        - name: data   # ref clusterdefinition components.containers.volumeMounts.name
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage:  {{ .persistence.data.size }}
      {{- end }}
      {{- $i = add1 $i }}
    {{- end }}
    {{- $j := 0 }}
    {{- range .Values.cn }}
    - name: cn-{{ $j }}
      componentDefRef: cn
      replicas: {{ .replicas }}
      {{- with  .resources }}
      resources:
        {{- with .limits }}
        limits:
          cpu: {{ .cpu | quote }}
          memory: {{ .memory | quote }}
        {{- end }}
        {{- with .requests }}
        requests:
          cpu: {{ .cpu | quote }}
          memory: {{ .memory | quote }}
        {{- end }}
      {{- end }}
      {{- if .persistence.enabled }}
      volumeClaimTemplates:
        - name: data   # ref clusterdefinition components.containers.volumeMounts.name
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: {{ .persistence.data.size }}
      {{- end }}
      {{- $j = add1 $j }}
      {{- end }}